apiVersion: v1
kind: Secret
metadata:
  name: octank-secrets
type: Opaque
data:
   DATABASE_URL: {{ .Values.config.db_url | b64enc }}
   DEFAULT_FROM_EMAIL: {{ .Values.config.from_email | default "support@octank.zethian.com" | b64enc }}              
   EMAIL_URL: {{ .Values.config.email_url | b64enc }}
   SECRET_KEY: {{ .Values.config.secret_key | default "291f7ed0*3208o4255$befa//44db82825246" | b64enc }}   
   AWS_ACCESS_KEY_ID: {{ .Values.config.aws.key_id | b64enc }}
   AWS_SECRET_ACCESS_KEY: {{ .Values.config.aws.access_key | b64enc }}

        