apiVersion: v1
data:
  nginx.conf: |
    worker_processes auto;
    pid /run/nginx.pid;

    events {

    }

    http {
        server {
            listen 80;
            server_name localhost 127.0.0.1;
            
            location /graphql/ {
                keepalive_timeout 0;

                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header Host $http_host;
                
                # disable cache
                proxy_no_cache 1;
                # even if cached, don't try to use it
                proxy_cache_bypass 1; 

                # we don't want nginx trying to do something clever with
                # redirects, we set the Host: header above already.
                
                proxy_pass http://localhost:8000/graphql/;

                # forbid all proxy_redirect directives at this level
                proxy_redirect off;
                proxy_set_header Connection ""; 
                
                add_header Last-Modified $date_gmt;
                add_header Cache-Control 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';
                if_modified_since off;
                expires off;
                etag off;               
            }

            location / {

                add_header Last-Modified $date_gmt;
                add_header Cache-Control 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';
                
                if_modified_since off;
                expires off;
                etag off;      
                             
                access_log off;
                return 200 "OK\n";
            }
        }
    }
kind: ConfigMap
metadata:
  name: octank-config
  labels:
    {{- include "store.labels" . | nindent 4 }}
