apiVersion: v1
kind: Service
metadata:
  name: {{ include "store.fullname" . }}-api
  labels:
    {{- include "store.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.octank.type }}
  ports:
    - port: {{ .Values.service.octank.port }}
      protocol: TCP
      targetPort: 80
      name: api
      nodePort: {{ .Values.service.octank.nodePort }}
  selector:
    {{- include "store.selectorLabels" . | nindent 4 }}